version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
    command: >
      sh -c "
      mongod --bind_ip_all &
      sleep 10 &&
      mongoimport --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray &&
      wait
      "

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongo


  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"